### PR TITLE
adding lookout as thanks sponsor

### PR DESCRIPTION
**Pull request by anapsix**
- updating header to Boston 2016
- adding lookout logo
- updating Dockerfile with extra package

### CODE REVIEW

**Comment by anapsix** [comment]
@demobox merge, pending your approval

**Comment by demobox** [comment]
@anapsix: Thanks! Was trying to test this (5a3ea12) but

http://45.55.223.18:54652/2016-boston-home/#sponsors

and the rest of the site looks down :-( Reverting the PR doesn't seem to fix it, so I was wondering if you've changed something in the underlying system..?

**Comment by anapsix** [comment]
fixing..

**Comment by demobox** [comment]
> fixing..

Thanks!

**Comment by demobox** [comment]
```
X /var/www/backup does not exist
```

apparently..? ;-)

**Comment by anapsix** [comment]
nah.. that showed up after merging `grav-update`.. 
it was in a weird state.. 
all good now

**Comment by demobox** [comment]
Happy days - thanks!

**Comment by anapsix** [comment]
if you make that logo 45 in height, it will look about as large as the first one, btw

**Comment by demobox** [comment]
> if you make that logo 45 in height, it will look about as large as the first one, btw

I was going to bottom-align them as on for [Boston 2015](http://45.55.223.18:54652/#sponsors) and [NYC 2015](http://45.55.223.18:54652/2015-nyc-home/#sponsors) - what do you think?

**Comment by anapsix** [comment]
I think, it looks good

**Comment by demobox** [comment]
> I think, it looks good

Thanks for checking!

**Pull request merged**
